### ISSUE TITLE
[Bug]: Uncontrolled error when executing a TX

### ISSUE THREAD

**Issue by racitores** [MetaMask/metamask-mobile#12696]
### Describe the bug

Android (crash) and iOS (uncontrolled error) app failed as a result of a custom transaction with low gas. Using STX on uniswap.

Note: the first time it happened, the application crashed (android) and when we tried to open it again, it requested to reset, going again to the SRP process and loosing all previous logs / info. We weren't able to reproduce it again

### Expected behavior

The tx should fail, and be listed as fail in the Activity tab

### Screenshots/Recordings

https://github.com/user-attachments/assets/1dd8deb7-e6b2-4836-b93a-7466be87ec53

![Image](https://github.com/user-attachments/assets/1b8d507d-bfac-4cfa-be2d-6a3faebc6b4c)
![Image](https://github.com/user-attachments/assets/589a096e-e724-4482-b179-2a5b3ba674e0)
![Image](https://github.com/user-attachments/assets/fda3df4a-b8b1-4f99-8cbf-87eca4ef1545)

### Steps to reproduce

1. Go to uniswap
2. swap eth for weth (mainnet)
3. accept on uniswap
4. on MM select custom config -> gas
5. add very low values (the closest to 0 allowed by the app)
6. Accept the tx
7. the error should appear

Check the video for more detail and error output

### Error messages or log output

```shell
Included in the screenshots/recording area of this issue
```

### Detection stage

During release testing

### Version

7.38.0

### Build type

None

### Device

Android

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

It happen on both Android and iOS

### Severity

sev2

**Comment by forest-diggs-consensys** [comment]
Reassigning to confirmations team - users should not be able to click/tap save when inputting invalid params for gas

**Comment by sleepytanya** [comment]
Might it be related to [Intrinsic gas too low bug]( https://github.com/MetaMask/metamask-mobile/issues/12612), that was fixed yesterday by @OGPoyraz?

Swap either fails on iOS with low gas fees:

https://github.com/user-attachments/assets/52c1af5d-fe66-4485-b5f2-d4c223523ca6


<img width="464" alt="Image" src="https://github.com/user-attachments/assets/7c04057e-dd3a-4850-a5ab-a1497b6d76a8" />

or iOS crashes:


https://github.com/user-attachments/assets/87ddb909-b485-45a2-bfb3-875bc11a9050



Android seems to always quit with low swap  gas fees:


https://github.com/user-attachments/assets/5f1a05a9-6af1-49b4-ab7b-9842df2a1b92


Error message:


<img width="494" alt="Image" src="https://github.com/user-attachments/assets/b2aac4a2-afc2-4a21-bc31-3acfce7c75cd" />

**Comment by sleepytanya** [comment]
Tried on branch with fix for Intrinsic gas too low bug - the issue occurs in this build too , with the same error message:

https://github.com/user-attachments/assets/70339a8e-81bd-468d-80ec-e5018e05e8f8

**Comment by sleepytanya** [comment]
Bug is present on other Popular networks too.

**Comment by sleepytanya** [comment]
This issue is present in 7.37.1:

https://github.com/user-attachments/assets/e65d551b-d740-4277-b154-732d1678d2b9

**Comment by Unik0rnMaggie** [comment]
Not present on [v7.39.0 (1529)](https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/2bc741ec625d2b84/public-install-page/5c00e20345132f5c0ba62601b0561034)

https://github.com/user-attachments/assets/9bbb1679-4f33-4c4d-9bc4-ef3a7a7ba3ca

https://github.com/user-attachments/assets/54530f4e-c152-4bdf-bf94-45be774bce9d

**Comment by vpintorico** [comment]
Hi @Unik0rnMaggie, since this issue is not present in 7.39.0. Can we close it?

**Comment by Unik0rnMaggie** [comment]
Hi @vpintorico I believe so! 

With the latest RC7.39.0 (1535) on Ethereum Mainnet, when setting custom gas too low, the Tx is cancelled, there is no error:

Hi @racitores Can we close this issue if the error is not present in v7.39.0?

https://github.com/user-attachments/assets/ac96437f-7a4c-433e-9d08-310a808f8c41

https://github.com/user-attachments/assets/4cf46af1-338c-46dd-9878-7a855f26f09d

**Comment by vinistevam** [comment]
Hey @Unik0rnMaggie, could you try setting the gas limit to `21000`? 🙏 
I believe this is an old issue since 7.35-34 , hopefully, It is fixed but it is worth to double check with those values. It will trigger the RPC error and cause the issue.

**Comment by cryptotavares** [comment]
RCA: https://www.notion.so/metamask-consensys/Bug-Uncontrolled-error-when-executing-a-TX-12696-185f86d67d6880a4b43ede6077f44d2d

FYI @vpintorico @jvbriones

**Comment by Unik0rnMaggie** [comment]
Hi @vinistevam, 

Apologies for my late reply! 

You are right, for  gas limit `21000` the same error is triggered as in [this issue](https://github.com/MetaMask/metamask-mobile/issues/12612), closed now. 

https://github.com/user-attachments/assets/f18a5ebe-1158-423a-ae8b-42b003217757

**Comment by Unik0rnMaggie** [comment]
Hi Team,

it seems the error is still present in v7.39.0 (1539):

https://github.com/user-attachments/assets/4f5235af-c140-4962-8b1a-5a731fe71985


It is also present in the build from [here](https://github.com/MetaMask/metamask-mobile/pull/13138#issuecomment-2609804921):

https://github.com/user-attachments/assets/f2306a0f-921d-441b-af1d-ce00847231d7

**Comment by Unik0rnMaggie** [comment]
The error is present, but it is the "correct error", when we are setting the gas to `21000` 

Before the fix, the error was crashing the app and not saving the transaction in the activity list.

Thank you very much for the info, @vinistevam! 🙏
