### ISSUE TITLE
Sync with extension doesn't work on my device

### ISSUE THREAD

**Issue by dzek69** [MetaMask/metamask-mobile#2112]
**Describe the bug**
Syncing with extension doesn't work. After I scan QR code I can see on the extension "Sync in progress" - it disappears after a minute and on mobile I can see "Please wait while we sync your data" screen that goes for many many minutes (I've tried over 10 minutes for 3 times) but nothing happens.

I suspect some error happens but it's not handled properly, so user isn't getting any feedback or something deep inside is really really slow (I'm on a cheap Chinese phone, but it can't be THAT bad) but there is no real progress indicator so I have no idea if that's the case.

App reacts properly to back button when it's stuck and is working just fine on my second device.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. On the main scren tap `Get Started`, then `Sync with Metamask extension`
2. Follow the steps on the screen
3. Scan the code
4. Wait until you think it's enough waiting and it's time to fix the bug :)

**Expected behavior**
Sync should finish and I should be presented with my wallets.

**Smartphone (please complete the following information):**
 - Device: Cubot Note 20 PRO
 - OS: Android 10
 - App Version 1.0.8 (taken from Settings (Apps list), so from some kind of manifest file, not from UI, because I cannot access it from UI before syncing, but i guess it should match anyway)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
Hi @dzek69 Sorry to hear this feature isn't working on one of your devices. Since the feature is working on other devices, it will be hard to reproduce and investigate on our side.
Please try again by reinstalling the app and ensuring you are on the latest version.

**Comment by dzek69** [comment]
I expected some tips to help you debug this issue, but okay

**Comment by ibrahimtaveras00** [comment]
@dzek69 some things I can suggest that may help:
1.  Expand your extension to be on the full browser view

![image](https://user-images.githubusercontent.com/41752922/106081093-546b6100-60e6-11eb-91f6-e73c48d9ad40.png)

2. When you get to the sync with mobile view, refresh/reload the page 

![image](https://user-images.githubusercontent.com/41752922/106081244-8aa8e080-60e6-11eb-8993-ca2b7d58f7ff.png)

3. Enter your password and attempt to sync with your mobile device 

If that doesn't work, try on a different browser if you feel comfortable importing your current wallet to a different browser.

**Comment by crawben20** [comment]
I'm encountering a similar issue through the Brave browser - it just spins on "Sync in progess" and then eventually reports on the phone that the QR code has expired. I do it all in a matter of seconds so I can't see how this can be the case.

**Comment by tylr-r** [comment]
Same issue on Brave browser

**Comment by ameisenmann** [comment]
Same issue here. Synching with mobile runs forever and then after a while a message is shown that QR code is expired. When I open the app again it loops in synching mode but nothing happens.
After re-installing the app I can scan the QR code but again hangs at synching...

Browser: 78.8.0esr (64-Bit)
Device: Google Pixel 2
Android version: 11
App-Version: 1.0.11

**Comment by diabaths** [comment]
> Same issue here. Synching with mobile runs forever and then after a while a message is shown that QR code is expired. When I open the app again it loops in synching mode but nothing happens.
> After re-installing the app I can scan the QR code but again hangs at synching...
> 
> Browser: Firefox 78.8.0esr (64-Bit)
> Device: Google Pixel 2
> Android version: 11
> App-Version: 1.0.11

Same with me, I use Firefox and I have the same behave

**Comment by ameisenmann** [comment]
I was able to narrow down the problem to the possible cause.
I added a custom network and custom token.
My brother who had not problems before then also added the custom network and he had the same issue.

At some point we were able to sync after repeating the following steps.
- Logout of Metamask in Firefox and close browser.
- Clear the cache and storage space of Android App
- Open Firefox and login to Metamask Wallet
- Go to settings-> advanced and select synch with mobile
- Start the App on your mobile and synch with Firefox extension
- Scan QR Code and pray

Hope that works for some of you.

**Comment by PellyXing** [comment]
I'm having this exact same issue.  I tried all the "fixes" here and it just wont sync.  Keeps saying it's an expired QR Code.  I am at a standstill until you guys can fix the bug.

**Comment by marcozambini** [comment]
Experiencing same problem here after scanning QR code in Chrome extension using iPhone 11 

![image](https://user-images.githubusercontent.com/14091649/111028768-b6ccb680-8433-11eb-8c04-80ff574bb803.jpeg)

**Comment by stormmuller** [comment]
Just started using Meta mask yesterday and ran into this issue. It only worked once I used the expanded view and refreshed the sync view as @ibrahimtaveras00 pointed out.

**Comment by duncanmwurphy** [comment]
Ran into this issue on my iPhone as well. I simply uninstalled the app and reinstalled and it worked right away. Give that a try.

**Comment by omnat** [comment]
Hi everyone, thanks for sharing - the fix for this issue will be released in the upcoming version.

**Comment by diosarris** [comment]
@omnat: Hello there, could you please share which version would that be so that we can follow up? Do you have any rough estimate on the release date?


I have the same issue with: 
Desktop: Brave 1.21.77 (Windows 10.0.19041) 
Mobile One Plus 5T , OS: Oxygen OS 10.0.1
Metamask mobile app version: 1.0.11  

Thank you in advance.

**Comment by scibuff** [comment]
Why is this issue closed? This has not been fixed! 

Desktop: Windows 10 Pro N (19042.867)
Browser: Version 89.0.4389.82 (Official Build) (64-bit)
Mobile: Galaxy S10+ OS: Android 11 (Kernel: 4.14.113-21054248)
Metamask mobile app version: 1.0.11

**Comment by ibrahimtaveras00** [comment]
Version 2.0.1 should be live soon on both OS's and that should resolve most syncing issues
If you continue to experience issues after checking back on version 2.0.1 please reopen

**Comment by asfand444** [comment]
I was having the same issue connecting chrome to mobile app. hopped to firefox, linked my account firefox and then scanned qr code from firefox to phone. It worked!

**Comment by bneiluj** [comment]
Same issue on Iphone 12 Pro Max with `2.0.1` and Desktop version `9.2.0`. 

Desktop: `Your data has been synced successfully. Enjoy the Matamask mobile app`

Phone: `Please wait while we sync your data...` Forever.

**Comment by duongkta** [comment]
I sync Metamask app on Android app with laptop extension version but it was not completed: on laptop extension inform syncing done but on Android app it is pending day by day no complete.
I have 1 another android smartphone synchronized with this extension account before, is this reason?
The smartphone which I'm trying to sync is Samsung Galaxy A72 (Android 11).
Metamask android version 2.0.1
Thank you guys for your supports.

**Comment by atmamont** [comment]
After the last update it doesn’t ask to wait anymore but the spinner still spins forever

**Comment by rrzadzki** [comment]
I'm also experiencing this issue. Firefox 87 on Ubuntu / MetaMask for Android on a Pixel 3A.

Followed the steps at https://github.com/MetaMask/metamask-mobile/issues/2112#issuecomment-768752302 to ensure the login and QR code were fresh. Watched both devices spin on "Syncing..." for about a minute, then phone reports the QR code is expired.

@dzek69 Consider reopening, there's enough reproductions to show this is a real issue.

**Comment by punto-** [comment]
I have the same issue today on Chrome 90.0.4430.93 with metamask version 9.4.0, and metamask mobile on Android version 2.2.0. I also have a custom network (binance) and some custom tokens on my chrome extension

**Comment by Donsabai** [comment]
My MetaMask 9.4.0 Chrome Extension shows all tokens but it will not sync with my iPhone 14.5.1 to show all tokens on iPhone. I have deleted the iPhone app twice and reinstalled and 'sync'd' to the Chrome extension. At this point I cannot see all my tokens on my iPhone. I only see the original leftover ETH but not the tokens I swapped for. NOTE: I copied the contract onto the Chrome Extension and not onto the Mobile. All tokens show up on Chrome Extension.

**Comment by eliotstock** [comment]
Why has this not been reopened? I can repro with:

Chrome 90.0.4430.93 (Official Build) (64-bit)
Android app v 2.2.0

**Comment by caretak3r** [comment]
> @dzek69 some things I can suggest that may help:
> 
>     1. Expand your extension to be on the full browser view
> 
> 
> ![image](https://user-images.githubusercontent.com/41752922/106081093-546b6100-60e6-11eb-91f6-e73c48d9ad40.png)
> 
>     1. When you get to the sync with mobile view, refresh/reload the page
> 
> 
> ![image](https://user-images.githubusercontent.com/41752922/106081244-8aa8e080-60e6-11eb-8993-ca2b7d58f7ff.png)
> 
>     1. Enter your password and attempt to sync with your mobile device
> 
> 
> If that doesn't work, try on a different browser if you feel comfortable importing your current wallet to a different browser.

For anyone landing up here in 2021+, **this works**. repro'd on chrome and firefox (dev edition).

**Comment by rrzadzki** [comment]
Fixed for me!

Firefox 87.0
Metamask extension 9.4.0
Metamask for Android 2.2.0

**Comment by dstaley** [comment]
> @dzek69 some things I can suggest that may help:
> 1.  Expand your extension to be on the full browser view
> 
> ![image](https://user-images.githubusercontent.com/41752922/106081093-546b6100-60e6-11eb-91f6-e73c48d9ad40.png)
> 
> 2. When you get to the sync with mobile view, refresh/reload the page 
> 
> ![image](https://user-images.githubusercontent.com/41752922/106081244-8aa8e080-60e6-11eb-8993-ca2b7d58f7ff.png)
> 
> 3. Enter your password and attempt to sync with your mobile device 
> 
> If that doesn't work, try on a different browser if you feel comfortable importing your current wallet to a different browser.

Just wanted to chime in and say these steps worked for me as well. I guess the trick is reloading the password page.

**Comment by sfchang92** [comment]
> @dzek69 some things I can suggest that may help:
> 
> 1. Expand your extension to be on the full browser view
> 
> ![image](https://user-images.githubusercontent.com/41752922/106081093-546b6100-60e6-11eb-91f6-e73c48d9ad40.png)
> 
> 1. When you get to the sync with mobile view, refresh/reload the page
> 
> ![image](https://user-images.githubusercontent.com/41752922/106081244-8aa8e080-60e6-11eb-8993-ca2b7d58f7ff.png)
> 
> 1. Enter your password and attempt to sync with your mobile device
> 
> If that doesn't work, try on a different browser if you feel comfortable importing your current wallet to a different browser.

Still happened for me. Have to fail one time and follow the above steps to workaround the issue.

Metamask extension 9.5.4
Metamask Android 2.3.0 (715)
Brave 1.24.86 Chromium: 90.0.4430.212 (Official Build) (64-bit)

**Comment by mitchschwartz** [comment]
I've just had this issue, between windows 10/brave and pixel 5. 

Resolved by retrying 6 times.

**Comment by luizzalaf** [comment]
I was having the same issue. 
Phone: Samsung/Android;
Computer: Windows/Chrome. 

I resolved after trying many times in the expanded view setting with the reload button.

**Comment by RoShamBoo** [comment]
I'm having the same issue.  Scan just hangs and sometimes I get the following PoP message: "Looks like you’re trying to scan a QR code, you need to unlock your wallet to be able to use it."  I've tried the suggested reload but not working.  Anyone got tips when you see that message?  THANKS!

Using Chrome extension and Mobile MM App 2.5.0

**Comment by Martin91** [comment]
Encountered the exactly same issue, but it finally back to normal after my 4 retries.

**Comment by Roopal-dev** [comment]
Tried to scan the code on both chrome and firefox browser,but still getting timeout error.(After 5 to 10 minustes of retry getting QR code is expired)
Device -Iphone 7.

Any help would be appreciated.Thanks in advance

**Comment by alanokelly** [comment]
Same issue here. Android Pixel 3. Chrome OS

**Comment by PrieurA** [comment]
Hi. I can't even write my password on metamask desktop to show the QRcode 😕
I have everything uptodate, chrome, metamask and my ledger.
<img width="382" alt="Capture d’écran 2021-10-05 à 00 09 12" src="https://user-images.githubusercontent.com/47487590/135931512-cc8a509b-df56-4ed1-85f6-25e23e6405de.png">

**Comment by IIIskiplikIII** [comment]
Hi, I have the same issue as @PrieurA has. I can't even proceed to the QR-Code via the button "next"

**Comment by IIIskiplikIII** [comment]
Thanks for the info @thangtran2012 
That explains a lot. So there is a workaround.

**Comment by NWcodeart** [comment]
> ![image](https://user-images.githubusercontent.com/2548001/136325776-1cefd12c-d959-4cf8-872a-aebf39f7f499.png) I just got this message.
> 
> Chrome Version 94.0.4606.71 (Official Build) (64-bit) on Windows10

did you find solution for this problem? it's happened to me too

**Comment by chiragnahata** [comment]
Same issue here
