### ISSUE TITLE
[Bug]: Total aggregated balance incorrect - the native token balance is not added

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-mobile#22775]
**Describe the bug**

On v7.60.0 (3047) the total aggregated balance is incorrect: the native tokens balance is not added (in both All popular network view and single network view) for the following networks:

Ethereum Mainnet, Base, Arbitrum, BNB, OP, Polygon.

Unable to reproduce for Linea, Avalanche, Solana, BTC

Unable to reproduce on Android, only iOS

State logs iOS:

[state-logs-v7.60.0-(3047).json](https://github.com/user-attachments/files/23579705/state-logs-v7.60.0-.3047.json)

**Expected behavior**

Total balance to include all tokens balances

**Screenshots/Recordings**

https://github.com/user-attachments/assets/eb7d19a2-3394-4c83-838e-99e1eb72beec

![Image](https://github.com/user-attachments/assets/3f17d939-08b3-4415-b2ee-1b7eac93f7c5)

![Image](https://github.com/user-attachments/assets/965ec151-a34d-4005-bdf8-0edb05c3d4aa)

<img width="1267" height="916" alt="Image" src="https://github.com/user-attachments/assets/0ce76009-2d0d-4b28-aa60-5bf3acbe9598" />

<img width="1265" height="917" alt="Image" src="https://github.com/user-attachments/assets/f8172aff-f077-456b-8c77-7bed6327bd9f" />

**Steps to reproduce**

1. Install v7.60.0 (3047)
2. Notice incorrect balances

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

7.60.0

**Build type**

None

**Device**

iPhone 15

**Operating system**

iOS

**Comment by Prithpal-Sooriya** [comment]
Did some testing, not able to replicate.
Note - there are related issues around either ERC token balances not updating vs native token balances not updating.

Will inspect the state logs

**Comment by Unik0rnMaggie** [comment]
Hi @Prithpal-Sooriya , thank you very much for checking!

I am able to reproduce consistently on the RC builds that have the _Restore needed_ issue.

See attached state logs and video of v7.60.0 (3093), as example.


However, I am unable to reproduce it on the latest RC build v7.60.0 (3094), where the _Restore needed_ issue has been fixed. 

Could they be related?

Should I downgrade to sev2? 


<img width="1262" height="924" alt="Image" src="https://github.com/user-attachments/assets/42ba3910-c7ac-4f11-ad2d-c9a404e9190e" />

https://github.com/user-attachments/assets/34d5bed8-fdaf-48a9-bfd4-b8317af2fa29

https://github.com/user-attachments/assets/00a8d42d-c414-4b59-b52e-59c154224905

[state-logs-v7.60.0-(3093).json](https://github.com/user-attachments/files/23625235/state-logs-v7.60.0-.3093.json)

[state-logs-v7.60.0-(3094).json](https://github.com/user-attachments/files/23625238/state-logs-v7.60.0-.3094.json)

**Comment by Prithpal-Sooriya** [comment]
@Unik0rnMaggie amazing! Yep this could be related (restore needed wipes some state/fields).

Will mark this down to a sev-2 (since we are working on other sev-1's). I'll keep an eye on this and look carefully at the restore functionality.

**Comment by Unik0rnMaggie** [comment]
Hi @Prithpal-Sooriya ! 

Just fyi: I was able to reproduce this issue on Android as well, using the following steps:

1. Remove network
2. Go to Advanced Settings and turn OFF Autodetect tokens
3. Re-add the network
4. Go to Advanced Settings and turn ON Autodetect tokens
5. Notice the native token balance is not added to the total aggregated balance

Should we re-add the `blocker` label in this case?

https://github.com/user-attachments/assets/bc6e4d4a-f29e-46db-a80e-9e75fe2d6cd6

State logs:

[457824632373398.txt](https://github.com/user-attachments/files/23628565/457824632373398.txt)

**Comment by Prithpal-Sooriya** [comment]
Still unable to replicate this issue.
https://www.loom.com/share/1d2c6315abdd4bb4a08a20b72c89c113

I tried both android and IOS 🤔 

Will do some more investigation

**Comment by Unik0rnMaggie** [comment]
Hi @Prithpal-Sooriya,

Thank you very much for checking! 

I was also unable to reproduce again, until I tried the following steps on iOS:

1. Fresh install of v7.60.0 (3108)
2. Notice balances are displayed correctly
3. Upgrade to v7.60.0 (3111)
4. Notice balances are still displayed correctly
5. Remove network
6. Turn OFF Autodetect tokens
7. Re-add the network
8. Notice aggregated balance is 0 but native token balance in the token list is not
9. Turn ON Autodetect tokens
10. Notice the native token balance is not added to the total aggregated balance

[Balance issue upgrade from 3108 to 3111 iOS Video
](https://drive.google.com/file/d/1Kq44pP7kFzSN_-mnZzbs-XDkyyZtNjV5/view?usp=sharing)

State logs: 

[state-logs-v7.60.0-(3111).json](https://github.com/user-attachments/files/23673631/state-logs-v7.60.0-.3111.json)

Unable to reproduce on android so far.

If you're still unable to reproduce with the above steps, please let me know so we can sync and maybe try together?

Thank you!

**Comment by Prithpal-Sooriya** [comment]
Core fix: https://github.com/MetaMask/core/pull/7216
Will create a patch for our controller.
