### ISSUE TITLE
Transaction Notification stuck at the bottom of the screen.

### ISSUE THREAD

**Issue by lsqproduction** [MetaMask/metamask-mobile#2494]
**Describe the bug**
 confirmed transaction pop-up (see screenshot) stuck on the bottom of the screen while using the browser. The pop-up itself doesn't block any interactions on websites, but when trying to interact with transfers approvals it somehow blocks the lower part of the screen, making interaction with payment/token approval impossible. 

**Screenshots**
![Screenshot_20210406_235434_io metamask](https://user-images.githubusercontent.com/12772017/114435532-e0d7dc80-9b89-11eb-9ca7-de2cb4aea926.jpg)

**To Reproduce**
_Steps to reproduce the behavior_
Possible cause: switching/ powering off screens in the middle of a transaction. 

**Expected behavior**
Notifications go away after a while

**Smartphone (please complete the following information):**
 - Device: Android, honor 9x lite
 - OS: [9]
 - App Version 2.0.1

114580, 114790, 119616, 121008,15238
-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
**This blocks people from doing essential tasks, because the action buttons on dapps etc. are blocked because of this notification getting stuck there** 
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by roo-shy** [comment]
in some cases reinstalling helps but it happens again as soon as user get an incoming transfer from a third party dapps. Example: stake.axion.network
<img width="249" alt="Screen Shot 2021-04-12 at 12 40 25 PM" src="https://user-images.githubusercontent.com/13618162/114437541-4dec7180-9b8c-11eb-8404-c526ce39a64c.png">

> in my browser a transaction is stuck and it won't let me use the bottom half of the screen at all on both browser or to add a coin please see pics, on my ipad no problems on my Android it won't work

<img width="243" alt="Screen Shot 2021-04-12 at 12 42 57 PM" src="https://user-images.githubusercontent.com/13618162/114437853-ade31800-9b8c-11eb-95a1-5ed8bf89555a.png">

**Comment by TuxieMeow93** [comment]
It's occurring for me as well, on iOS. ![image](https://user-images.githubusercontent.com/4273713/115047438-818a0d00-9ea6-11eb-8488-96b02a05130e.png)

**Comment by mobularay** [comment]
@rickycodes @omnat was this issue supposed to have been fixed in v2.2? This ticket does not look brand new, even though it was opened 17 days ago. Will you be using the same PR 2485 or creating a new one?

**Comment by mobularay** [comment]
Re-opening this ticket as v2.2 did not fix this issue

**Comment by eddfr** [comment]
While "transaction submitted" is stuck in the browser, funds CANNOT be send via "assets" as the "Next" button becomes unresponsive after entering destination address.

Furthermore, buttons in the browser also do not respond, making use of wallet connect in-browser also impossible. 

This in effect freezes user funds.
(Not fixed by 2.2)

**Comment by mobularay** [comment]
Thanks for sharing the details here, @eddfr. Our team is currently working on this issue, any additional info/details will help us at this point. 

We'll keep you (all) updated in the next while.

**Comment by eddfr** [comment]
Should the "unpressable buttons" issue be opened as a new issue?
@mobularay ?

**Comment by mobularay** [comment]
@eddfr good point. I am not sure. Let me speak with the team first and update you. Thank you!

**Comment by cfal** [comment]
I'm seeing this happen on Android, MetaMask v2.2.0 (54). I've seen the transaction notification as "Transaction XX Complete!" like in the above screenshots, as well as "transaction submitted", like in the screenshot below. Unfortunately, none of "Reset Account", "Clear privacy data", "Clear browser history", or "Clear browser cookies" fixes it, I had to reinstall each time. I think this usually happens when a transaction is running, but before confirmation, I close the app or switch to another app, and then return to it.

<img width="363" alt="Screen Shot 2021-05-12 at 9 34 06 PM" src="https://user-images.githubusercontent.com/14366446/117975716-ed5a7b00-b369-11eb-939c-c2cfa3204a96.png">

**Comment by eddfr** [comment]
Found this bug on: Vivo phone
Metamask: version previous to 2.20, persisting after update to 2.20
Phone OS: 
funtouchOS
vivo rev 1.56.25

**Comment by sevet** [comment]
Have this stuck transaction screen for a while but does nt want to reinstall, its like it there and not there, browser buttons work through it - home, back etc' but cant confirm transactions.
For the time being i istalled kiwibrowser with regular metamask chrome extension.
Android 11

**Comment by mobularay** [comment]
@cfal @eddfr @sevet - thank you for your responses! I will check-in with my team to see if they need more info in order to (re-) start troubleshooting again. Will keep you posted.

**Comment by mobularay** [comment]
A few more questions:
1. can you share your state logs with us, asap (sorry I should have asked for this earlier) or when this issue happens again to you?
2. @sevet, is your description relating to your usage with Extension or the Mobile app? 
3. seems like you all are able to "come back" to the app after it froze by moving away from the MetaMask mobile app to a different app, and then coming back to it... and you can do this multiple times. Is this correct?

**Comment by sevet** [comment]
> A few more questions:
> 
> 1. can you share your state logs with us, asap (sorry I should have asked for this earlier) or when this issue happens again to you?
> 2. @sevet, is your description relating to your usage with Extension or the Mobile app?
> 3. seems like you all are able to "come back" to the app after it froze by moving away from the MetaMask mobile app to a different app, and then coming back to it... and you can do this multiple times. Is this correct?

Only on mobile version never on extension, this message is up a few weeks now its transaction 65 for me and im on 110 now, it stayed through reboots and upgrade, im just waiting for it to dissapear on some upgrade since i dont want to add all my networks and tokens back manually....(why not auto discover tokens?)
How can i send my logs privately?

**Comment by mobularay** [comment]
Hello @cfal @sevet @eddfr CC @roo-shy

Thank you for sharing your experiences, steps and conditions here (and also screenshots!) that you encountered when this issue appeared <3 They were really helpful, and we believed we found the root cause and identified the solution. I will update this thread again on the ETA of this bug fix being released to production so that you can get the latest version to overcome this issue. 

Stay tuned!
