### ISSUE TITLE
Confirm button not working

### ISSUE THREAD

**Issue by urkishan** [MetaMask/metamask-mobile#5260]
Confirm button not working while doing the transaction when using the WalletConnect.

IOS version : 16.1.1
IOS version : 16.0.3

**Comment by tommasini** [comment]
Hello @urkishan, thanks for reporting! We are aware and a fix will be released as soon as possible!

**Comment by amftokenofficial** [comment]
waiting...

**Comment by thekingcrobra** [comment]
This issue also happened in android version 5.10.0. 
Help me please.

**Comment by amftokenofficial** [comment]
I'm sorry, but I really can't wait any longer and be polite.
This is a really serious problem and I don't understand if there is anyone trying to solve it?
It's really not professional. There are several "open issues" - created here as well as on other platforms on this issue in the last 2-3 weeks.
Is this a minor bug for the MM team?
Wake up guys, this is really URGENT.

**Comment by livid** [comment]
Probably related: On this confirm-not-working page, if you click gas fee settings and save, it presents this 60E warning.

![IMG_31D11998DD58-1](https://user-images.githubusercontent.com/11427/202883785-39d2745d-b359-46ff-9ef3-5ec019cd9a7c.jpeg)

**Comment by terminatorbob** [comment]
Having the same issue on iOS.  This makes MetaMask basically useless for me.  This needs to be fixed ASAP.

**Comment by thekingcrobra** [comment]
In Android, I saw they have rollback to version 5.9.1.
So I can uninstall 5.10.0 and replace with 5.9.1 and it's work for me.

**Comment by waichung** [comment]
Having the same issue on iOS here. Anyone has a work around?

**Comment by amftokenofficial** [comment]
It's been over 22 days since I first submitted a ticket to MM support and still no reasonable response.
Maybe we need to forget MM? and completely switch to another wallet and ask our users to do the same?
I really don't understand how it can be that such a company is ignoring this serious issue.
There are over 4 open issues here and a few others on stackoverflow.

**Comment by tommasini** [comment]
Thanks for your patience, a fix already have been developed, and it's about to be available in the stores on version 5.11.0 

In Android, until it is available you can download the apk of version 5.9.1 here on our GitHub repo https://github.com/MetaMask/metamask-mobile/releases/tag/v5.9.1

**Comment by blackdevelopa** [comment]
Thanks @tommasini for following up on this. This issue is now fixed and available in v5.11.0

**Comment by amftokenofficial** [comment]
for me it is still exists and not solved in 5.11.0. Is anybody still have the issue?

**Comment by tommasini** [comment]
@amftokenofficial thanks for coming in here, can you send more details please, like your device, the network you are using?
If you also could send to us a small record we appreciate it

**Comment by amftokenofficial** [comment]
> @amftokenofficial thanks for coming in here, can you send more details please, like your device, the network you are using? If you also could send to us a small record we appreciate it

I already did it. Sent to MM support (zendesk ticket).

**Comment by ClaireMao1996** [comment]
@tommasini I updated to the latest version and it still doesn't work on `Goerli Test Network` 
My device is Google pixel 6a, Android13

**Comment by tommasini** [comment]
Thanks, @ClaireMao1996 , could you confirm on settings -> About MetaMask if the version it's 5.11.0?
Also, can you describe the steps that you are doing to help us to reproduce it?

**Comment by ClaireMao1996** [comment]
https://user-images.githubusercontent.com/101389820/203557410-2668ab5f-b340-4b47-ba97-00f2b5a4c1ee.mp4

The easiest way to reproduce is to use the MetaMask browser to open [this link](https://goerli.etherscan.io/address/0xa7dE12A217Fc236a46c509Cea9b5BaB2d11b2344#writeContract) (or any other ERC20 token as well) then doing transfer.

**Comment by tommasini** [comment]
@ClaireMao1996 @amftokenofficial 
After we tried to replicate a BEP-20 and ERC-20 transaction, we couldn't reproduce the confirm button issue, let us know if there is something you notice that we could change to find this issue. Thanks!

We record it:
* ERC-20 https://recordit.co/HObMZRUh41
* BEP-20 https://recordit.co/OoFBV0BNTy

**Comment by amftokenofficial** [comment]
> @ClaireMao1996 @amftokenofficial After we tried to replicate a BEP-20 and ERC-20 transaction, we couldn't reproduce the confirm button issue, let us know if there is something you notice that we could change to find this issue. Thanks!
> 
> We record it:
> 
> * ERC-20 https://recordit.co/HObMZRUh41
> * BEP-20 https://recordit.co/OoFBV0BNTy

There is no any special things to reproduce. Get any token (smart contract) and process transfer on mobile (MM browser or MM app). It works on PC, but don't work on any mobile device.

**Comment by lutakrystal305** [comment]
> > @ClaireMao1996 @amftokenofficial After we tried to replicate a BEP-20 and ERC-20 transaction, we couldn't reproduce the confirm button issue, let us know if there is something you notice that we could change to find this issue. Thanks!
> > We record it:
> > 
> > * ERC-20 https://recordit.co/HObMZRUh41
> > * BEP-20 https://recordit.co/OoFBV0BNTy
> 
> There is no any special things to reproduce. Get any token (smart contract) and process transfer on mobile (MM browser or MM app). It works on PC, but don't work on any mobile device.

same issue

**Comment by tommasini** [comment]
@amftokenofficial On the record that I sent on this [comment](https://github.com/MetaMask/metamask-mobile/issues/5260#issuecomment-1325472254), I'm doing a transfer of BEP-20 (CAKE) with wallet connect and MetaMask mobile app (Also I tested with chrome mobile and MetaMask mobile, and the same expected behaviour it's happening)

**Comment by tommasini** [comment]
@amftokenofficial We also tested with AMF token https://recordit.co/DHun6zULS9

**Comment by amftokenofficial** [comment]
> @amftokenofficial We also tested with AMF token https://recordit.co/DHun6zULS9

Could you share the code? Maybe there is something that we don't use, but it's a must.

**Comment by pietrociatta** [comment]
I'm facing the same issue since the day the github issue has been opened there. 

All my customers are on mobile phone and with MetaMask mobile they are all saying "the confirm button doesn't work".

The transaction is a ERC20 transfer from the customer wallet to the company wallet.

Tell me if there's something you need from me to help you fix 🙏🏼

**Comment by konjoinfinity** [comment]
> Confirm button not working while doing the transaction when using the WalletConnect.
> 
> IOS version : 16.1.1 IOS version : 16.0.3

Confirming it's not just WalletConnect. I'm directly connected through the Metamask browser and experiencing this issue when confirming NFT mint transactions. Tap the blue "Confirm" button (not greyed out), and it doesn't do anything.

**Went to check my metamask version, and updated to 5.11.0. It now works from IOS 16.1.1!!!**

**Comment by amftokenofficial** [comment]
any news?

**Comment by Amoled** [comment]
+1, Please raise the priority of the problem. Many services can only be paid through WalletConnect, and the "Confirm" button has not been working for several weeks.

iOs 16, MetaMask 5.11.0

**Comment by chrisleewilcox** [comment]
We are trying to determine if this issue is caused by certain tokens as most have not experience this issue.  We continue to investigate.

**Comment by indeyets** [comment]
> We are trying to determine if this issue is caused by certain tokens as most have not experience this issue. We continue to investigate.

I see it with USDT over BEP20 network

**Comment by ClaireMao1996** [comment]
> We are trying to determine if this issue is caused by certain tokens as most have not experience this issue. We continue to investigate.

Or maybe caused by certain account/address? Because the same token we transfer by different account one works fine and the other not working.

**Comment by SaadNiaziDev** [comment]
Facing same issue with no error on 5.12.0 but it gives "invalid amount" error on 5.8.1.
Both devices that are used are Androids and network is Goerli

**Comment by tommasini** [comment]
@SaadNiaziDev Could you try to explain the steps that you took to reproduce it on goerli network?

**Comment by kaumudpa** [comment]
Same issue with Polygon Mumbai.

**Comment by amftokenofficial** [comment]
it's over a month and still we have no any solution?

**Comment by tommasini** [comment]
Thanks for the patient, like we show on previous comments, we are having difficulty on reproducing this issue

We appreciate any recording with all the steps to perform the transactions that are not working with the device info and metamask mobile app version attached 

Thank you again for the understanding and all the help to make metamask better

**Comment by Amoled** [comment]
> We appreciate any recording with all the steps to perform the transactions that are not working with the device info and metamask mobile app version attached

Again?
OK. My example.
Pyypl app.
0. I open.
2. Press "+ Top Up"
3. Select Binance from the list
4. Select "Light wallets" from the dropdown list
5. I press the big button for the full screen Top-up
6. I choose connected wallet MetaMask
7. Enter the amount of 200 USDT
8. Confirm
9. Opens automatically MetaMask
10. Automatically pops up the transfer confirmation window
11. The Reject button is white, it works - you press it and the window closes
12. The Accept button is blue, pressed (there is visual feedback when the button changes color when pressed) - nothing else happens.

iPhone 11, iOS 16.1.1, MetaMask v5.12.3 (1033), language English, Network BNB Smart Chain (https://bsc-dataseed1.binance.org), ChainID 56, Token USDT (token contract address 0x55d3... 7955).

What other information do you need to provide?
It's been two months since I've been unable to use the app. You have to manually transfer tokens to Binance, and pay for purchases from there. This is not serious!

**Comment by orangeqq** [comment]
1. [Macbook][Chrome]https://etherscan.io/address/0x377e0c5d3738FAcd2D4c1CA192c774e978E8e95b#writeContract
2. [Macbook][Chrome]Click 「Connect to Web3」
3. [Macbook][Chrome]Click「Wallet Connect」and the bar code will shown
4. [iPhone][MetaMask App] scan the bar code which is shown on the PC
5. [iPhone][MetaMask App] Approve the connect
6. [Macbook][Chrome] Click 「4. transfer」
7. [Macbook][Chrome] Paste the address for transfer to, and the amount 1000000000000000000(for 1 token)
8. [Macbook][Chrome] Click 「Write」button
9. [iPhone][MetaMask App] the request for approve of transaction window will shown on the Metamask App
10. [iPhone][MetaMask App] Click the 「Confirm」button. It doesn't work.

・It only happens when using 「wallet connect」
・If you want this token for reproducing, contact me and I will transfer some to you.
-------------------
Ethereum Mainnet
MacOS Monterey Version 12.0.1
Chrome Version 108.0.5359.124 (Official Build) (x86_64)
iPhone Xs, iOS 16.1.2
MetaMask v5.12.3 (1033)

**Comment by diyakirtan** [comment]
Hi , The connect button issue is still existing in metamask 5.12.1 version for Android phone.

**Comment by omarmoss** [comment]
The same problem exists when using mobile hotspot (Android HMS Core 6.11.0.332) as internet connection, when trying to make a swap using Metamask on my laptop.

Button remains faded indefinitely.

Laptop details:
Brave Browser [Version 1.56.14 Chromium: 115.0.5790.114 (Official Build) (64-bit)](https://brave.com/latest/)
+ Metamask version 10.34.0
