### ISSUE TITLE
[Bug]: ENS resolving to a wrong address when using a Deeplink for a Send

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5588]
**Describe the bug**
When I am performing a Send using  a Deeplink, the ENS resolves to a wrong address.

**Screenshots**
With a deeplink resolves to a wrong address, like this:

![deeplink-ens](https://user-images.githubusercontent.com/54408225/214266729-e5f9f430-dbe0-4b26-bccc-3f9394a95da1.png)

With a regular send resolves correctly, like this:
![ens-correct](https://user-images.githubusercontent.com/54408225/214266740-a011ffca-e119-4ea6-872e-aa8fba658b7d.png)

https://user-images.githubusercontent.com/54408225/214266659-4a1d662d-93b3-4555-bab0-47d23ce930ba.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Select Mainnet
2. Click on scanner
3. Scan this QR code (for seaona.eth)

![image](https://user-images.githubusercontent.com/54408225/214267027-e8ece620-3024-4fc2-aef1-1261b201f4d5.png)

4. See recipient address -- that's a wrong address
5. Cancel the Send
6. Click Send
7. Add recipient `seaona.eth`
8. Add amount
9. See recipient address -- the correct one

**Expected behavior**

- In case we support ENS domains on deeplinks, we should resolve to the correct address.
- In case we don't support ENS domains on deeplinks, we should display an error, when a ENS domain is passed.

**Smartphone (please complete the following information):**

- Device: Samsung SM-A217F
- OS: Android 11.0
- App Version: v5.12.3 (1033)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by seaona** [comment]
There is the same issue for a Token Transfer, see here https://github.com/MetaMask/metamask-mobile/issues/5176

**Comment by tommasini** [comment]
Hey @seaona thanks for reporting, I believe this issue was solved on 5.13.0, could you confirm this use case, please?

**Comment by seaona** [comment]
hi @tommasini thank you for your reply! Since I'm on Android, I still was on a previous version. I've just checked now on 5.13.0 version and I can see that Sending to an ENS address using Deeplinks is now fixed.
I've checked Transfer and it's also fixed, but for the Approve functionality with Deeplink, I can still see the ENS not resolving correctly. In this case it seems it's just showing some short hex value. See below:

https://user-images.githubusercontent.com/54408225/215760275-e9f43999-3140-4469-8d2c-32ebb7de8437.mp4

Please let me know if I should open a separate issue for that, so we can close this issue. Thank you!!
cc @blackdevelopa

**Comment by blackdevelopa** [comment]
Hey @seaona, thanks for this update. Really helps. I think it's a related but different issue. I can create a separate issue for this and assigned the same labels.
cc @tommasini

**Comment by tommasini** [comment]
@seaona great catch! 
Yes I agree @blackdevelopa  we should isolate the issue and give him a detailed description for easier debug and implementation

**Comment by seaona** [comment]
thank you both! I've created a new issue for that specific behavior @tommasini @blackdevelopa 
https://github.com/MetaMask/metamask-mobile/issues/5648

**Comment by blackdevelopa** [comment]
Thank you @seaona. Closing this issue now https://github.com/MetaMask/metamask-mobile/issues/5648
